# Generated by Django 3.1 on 2021-02-24 21:54

from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=30)),
                ('bulletin_board_instruction', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=30)),
                ('post_contents', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('bulletin_board_name', models.ForeignKey(db_column='board_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.bulletin_board')),
            ],
        ),
        migrations.CreateModel(
            name='us_info',
            fields=[
                ('account_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('student_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=250)),
                ('college_mail', models.EmailField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.us_info')),
                ('profile_image', models.ImageField(null=True, upload_to=mainApp.models.upload_profile_image)),
                ('nickname', models.CharField(max_length=15, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('introduction', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Image_Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=mainApp.models.upload_post_image)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.profile'),
        ),
        migrations.CreateModel(
            name='My_Board_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=30, null=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.post')),
                ('comment_text', models.TextField()),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='bulletin_board',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.profile'),
        ),
        migrations.CreateModel(
            name='Bookmarked_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=30, null=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.profile')),
            ],
        ),
    ]
