# Generated by Django 3.1.7 on 2021-02-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='us_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=250)),
                ('student_id', models.IntegerField()),
            ],
        ),
    ]
