# Generated by Django 3.1.7 on 2021-02-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='us_info',
            name='college_mail',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
